SET SCHEMA FN71959;


CREATE TABLE BRANCHES
(
    NAME VARCHAR(100) NOT NULL PRIMARY KEY,
    ADDRESS VARCHAR(300) NOT NULL
);

CREATE TABLE SERVICES
(
    NAME_PROCEDURE VARCHAR(100) NOT NULL PRIMARY KEY,
    PRICE DOUBLE NOT NULL,
    DURATION INTEGER NOT NULL,
    AREA VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(600)
);

ALTER TABLE SERVICES ADD CONSTRAINT CK_SERVICES_AREA CHECK (AREA IN ('първичен прием и консултация', 'терапевтични грижи', 'ваксинация', 'хирургични услуги и операции', 'стоматологични услуги', 'рентгенови изследвания', 'лабораторни изследвания'));
ALTER TABLE SERVICES ADD CONSTRAINT CK_SERVICES_PRICE CHECK ( PRICE > 0 );
ALTER TABLE SERVICES ADD CONSTRAINT CK_SERVICES_DURATION CHECK ( DURATION > 0 );

CREATE TABLE STAFF
(
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(300) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    WORK_NUMBER VARCHAR(10) NOT NULL PRIMARY KEY,
    VETERINARY_EDUCATION VARCHAR(300) NOT NULL,
    ADDITIONAL_QUALIFICATIONS VARCHAR(300),
    BRANCH_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT FK_STAFF_BRANCHES FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCHES(NAME)
);

CREATE TABLE CONSUMABLES
(
    NAME VARCHAR(100) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    TYPE_SUBSTANCE VARCHAR(40),
    EXPIRY_DATE DATE NOT NULL,
    PRODUCTION_NUMBER VARCHAR(14) NOT NULL PRIMARY KEY,
    BRANCH_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT FK_CONSUMABLES_BRANCHES FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCHES(NAME),
    CONSTRAINT CK_CONSUMABLES_QUANTITY CHECK ( QUANTITY > 0 )
);

CREATE TABLE CLIENTS
(
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(300) NOT NULL,
    PHONE VARCHAR(10) NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(50),
    CONSTRAINT CK_CLIENTS_EMAIL CHECK ( EMAIL LIKE '%_@__%.__%' OR EMAIL LIKE '')
);

CREATE TABLE ANIMALS
(
    NAME VARCHAR(100) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    SPECIES VARCHAR(40) NOT NULL,
    VACCINATIONS VARCHAR(400),
    CODE VARCHAR(12) NOT NULL PRIMARY KEY,
    LAST_VISIT DATE NOT NULL,
    CLIENT_PHONE VARCHAR(10) NOT NULL,
    CONSTRAINT FK_ANIMALS_CLIENTS FOREIGN KEY(CLIENT_PHONE) REFERENCES CLIENTS(PHONE)
);

ALTER TABLE ANIMALS ADD CONSTRAINT CK_ANIMALS_SPECIES CHECK (SPECIES IN ('куче', 'котка', 'заек', 'морско свинче', 'хамстер', 'таралеж', 'папагал'));

CREATE TABLE SERVES
(
    ANIMAL_CODE VARCHAR(12) NOT NULL,
    BRANCH_NAME VARCHAR(100) NOT NULL
);

ALTER TABLE SERVES ADD CONSTRAINT PK_SERVES PRIMARY KEY (ANIMAL_CODE, BRANCH_NAME);
ALTER TABLE SERVES ADD CONSTRAINT FK_SERVES_ANIMALS FOREIGN KEY (ANIMAL_CODE) REFERENCES ANIMALS(CODE);
ALTER TABLE SERVES ADD CONSTRAINT FK_SERVES_BRANCHES FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCHES(NAME);

CREATE TABLE PERFORMS
(
    SERVICE_NAME_PROCEDURE VARCHAR(100) NOT NULL,
    STAFF_WORK_NUMBER VARCHAR(10) NOT NULL
);

ALTER TABLE PERFORMS ADD CONSTRAINT PK_PERFORMS PRIMARY KEY (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER);
ALTER TABLE PERFORMS ADD CONSTRAINT FK_PERFORMS_SERVICES FOREIGN KEY (SERVICE_NAME_PROCEDURE) REFERENCES SERVICES(NAME_PROCEDURE);
ALTER TABLE PERFORMS ADD CONSTRAINT FK_PERFORMS_STAFF FOREIGN KEY (STAFF_WORK_NUMBER) REFERENCES STAFF(WORK_NUMBER);