SET SCHEMA FN71959;


CREATE VIEW EXPIRED_CONSUMABLES
AS SELECT *
FROM CONSUMABLES
WHERE EXPIRY_DATE < (SELECT CURRENT_DATE FROM SYSIBM.SYSDUMMY1)
WITH CHECK OPTION;

SELECT * FROM EXPIRED_CONSUMABLES;

CREATE VIEW DEPLETION_CONSUMABLES(CONSUMABLE, BRANCH, QUANTITY)
AS SELECT NAME, BRANCH_NAME, QUANTITY
FROM CONSUMABLES
WHERE QUANTITY < 15;

SELECT * FROM DEPLETION_CONSUMABLES;

CREATE VIEW CLIENTS_WITH_MORE_THAN_ONE_ANIMAL (CLIENT, PHONE, NUMBER_OF_ANIMALS)
AS SELECT C.NAME, CLIENT_PHONE, COUNT(*)
FROM ANIMALS A, CLIENTS C
WHERE A.CLIENT_PHONE = C.PHONE
GROUP BY CLIENT_PHONE, C.NAME
HAVING COUNT(*) >= 2;

SELECT * FROM CLIENTS_WITH_MORE_THAN_ONE_ANIMAL;