SET SCHEMA FN71959;

CREATE FUNCTION GETAGEANIMAL(P_CODE VARCHAR(12))
RETURNS VARCHAR(64)
BEGIN
    DECLARE YEARS INT;
    DECLARE MONTHS INT;
    DECLARE DAYS INT;

    SET YEARS = YEAR(CURRENT_DATE - (SELECT BIRTH_DATE FROM ANIMALS WHERE CODE = P_CODE));
    SET MONTHS = MONTH(CURRENT_DATE - (SELECT BIRTH_DATE FROM ANIMALS WHERE CODE = P_CODE));
    SET DAYS = DAY(CURRENT_DATE - (SELECT BIRTH_DATE FROM ANIMALS WHERE CODE = P_CODE));

    RETURN 'Години: ' || YEARS || ', Месеци: ' || MONTHS || ', Дни: ' || DAYS;
END;

SELECT NAME, FN71959.GETAGEANIMAL(CODE) AS AGE FROM ANIMALS;


CREATE FUNCTION ANIMALSPERCLIENT(P_CLIENT_PHONE VARCHAR(10))
RETURNS INT
    RETURN
        SELECT COUNT
        FROM (SELECT CLIENT_PHONE, COUNT(*) AS COUNT
              FROM ANIMALS
              GROUP BY CLIENT_PHONE)
        WHERE CLIENT_PHONE = P_CLIENT_PHONE;

SELECT CLIENT_PHONE, FN71959.ANIMALSPERCLIENT(CLIENT_PHONE) FROM ANIMALS;


CREATE FUNCTION ISVACCINATEDAGAINSTRABIES(P_CODE VARCHAR(12))
RETURNS VARCHAR(4)
BEGIN
    IF (SELECT VACCINATIONS FROM ANIMALS WHERE CODE = P_CODE
        AND VACCINATIONS LIKE '%Ваксинация против бяс%') IS NULL
        THEN RETURN 'Не';
    ELSE
        RETURN 'Да';
    END IF;
END;

SELECT NAME, VACCINATIONS, FN71959.ISVACCINATEDAGAINSTRABIES(CODE) FROM ANIMALS;