SET SCHEMA FN71959;

CREATE TRIGGER UNKNOWNSUBSTANCE
    BEFORE INSERT ON CONSUMABLES
    REFERENCING NEW AS N
    FOR EACH ROW
    WHEN (N.TYPE_SUBSTANCE = '')
    SET N.TYPE_SUBSTANCE = 'НЕИЗВЕСТНО';

INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Wonderful cure', 6, '', '16.10.2022', 'KBSGTN74031592', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Wonderful cure', 6, '', '09.11.2022', 'WESRTJ81021372', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Wonderful cure', 6, '', '28.09.2022', 'IQFGAN34631795', 'Пухкав свят - София');


CREATE TABLE ANIMALLOGS
(
    ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100),
    CODE VARCHAR(12),
    LAST_VISIT DATE,
    CLIENT_PHONE VARCHAR(10),
    RECORD_TIME TIME
);

CREATE TRIGGER CREATELOGS
    AFTER UPDATE OF LAST_VISIT ON ANIMALS
    REFERENCING OLD AS O NEW AS N
    FOR EACH ROW
    INSERT INTO ANIMALLOGS(NAME, CODE, LAST_VISIT, CLIENT_PHONE, RECORD_TIME)
    VALUES (N.NAME, N.CODE, N.LAST_VISIT, N.CLIENT_PHONE, CURRENT_TIME);

UPDATE ANIMALS
SET LAST_VISIT = '19.12.2021'
WHERE CODE = '010568817747';


CREATE TRIGGER UPDATELASTVISIT
    AFTER UPDATE OF VACCINATIONS ON ANIMALS
    REFERENCING OLD AS O NEW AS N
    FOR EACH ROW
    WHEN (O.VACCINATIONS <> N.VACCINATIONS)
    UPDATE ANIMALS
    SET LAST_VISIT = CURRENT_DATE
    WHERE CODE = O.CODE;

UPDATE ANIMALS
SET VACCINATIONS = 'Моновалентна  P ваксина, Ваксинация против бяс'
WHERE CODE = '010568817747';


CREATE TRIGGER SHOWINFOABOUTSTAFF
    AFTER INSERT ON STAFF
    REFERENCING NEW AS N
    FOR EACH ROW
    BEGIN
        DECLARE NUMBEROFEMPLOYEES INT DEFAULT 1;
        DECLARE COUNTER INT DEFAULT 0;
        DECLARE RECORD ANCHOR ROW STAFF;
        DECLARE loc RESULT_SET_LOCATOR VARYING;

        CALL FN71959.INFORMATIONEMPLOYEES(N.BRANCH_NAME);
        ASSOCIATE RESULT SET LOCATOR (loc) WITH PROCEDURE FN71959.INFORMATIONEMPLOYEES;
        ALLOCATE CURSORSTAFF CURSOR FOR RESULT SET loc;

        SELECT COUNT(*) INTO NUMBEROFEMPLOYEES FROM STAFF WHERE BRANCH_NAME = N.BRANCH_NAME;

        WHILE COUNTER < NUMBEROFEMPLOYEES DO
            FETCH FROM CURSORSTAFF INTO RECORD;
            CALL DBMS_OUTPUT.PUT_LINE(RECORD.NAME || ' | ' || RECORD.WORK_NUMBER
                                                  || ' | ' || RECORD.BRANCH_NAME
                                                  || ' | ' || RECORD.VETERINARY_EDUCATION);
            SET COUNTER = COUNTER + 1;
        END WHILE;

        CLOSE CURSORSTAFF;
    END;

INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Даниел Еспиноза', 'гр. Велико Търново, ул. Черни връх 74', '0884623061', '0884719357', 'Тракийски университет в гр. Стара Загора', 'Сертификат по вътрешна медицина', 'Пухкав свят - Велико Търново');


CREATE TRIGGER GETVOUCHER
    AFTER INSERT ON ANIMALS
    REFERENCING NEW AS N
    FOR EACH ROW
    BEGIN
        DECLARE V_SPECIES ANCHOR ANIMALS.SPECIES;
        DECLARE V_BRANCH_NAME ANCHOR BRANCHES.NAME;
        DECLARE V_ADDRESS ANCHOR CLIENTS.ADDRESS;
        DECLARE COUNT_SPECIES INT DEFAULT 0;
        DECLARE COUNT_SPECIES_PER_BRANCH INT DEFAULT 0;
        DECLARE COUNTER INT DEFAULT 0;
        DECLARE COUNT_ROWS INT DEFAULT 1;
        DECLARE CURSORBRANCHES CURSOR FOR SELECT NAME FROM BRANCHES;

        SET V_SPECIES = N.SPECIES;
        SELECT ADDRESS INTO V_ADDRESS FROM CLIENTS WHERE PHONE = N.CLIENT_PHONE;

        IF V_ADDRESS LIKE '%София%' THEN INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME)
                                         VALUES (N.CODE, 'Пухкав свят - София');
        ELSEIF V_ADDRESS LIKE '%Варна%' THEN INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME)
                                             VALUES (N.CODE, 'Пухкав свят - Варна');
        ELSEIF V_ADDRESS LIKE '%Велико Търново%' THEN INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME)
                                                      VALUES (N.CODE, 'Пухкав свят - Велико Търново');
        END IF;

        SELECT COUNT(*) INTO COUNT_ROWS FROM BRANCHES;
        OPEN CURSORBRANCHES;

        WHILE COUNTER < COUNT_ROWS DO
            FETCH FROM CURSORBRANCHES INTO V_BRANCH_NAME;
            CALL FN71959.FINDNUMBEROFSPECIES(V_SPECIES, V_BRANCH_NAME,
                                             COUNT_SPECIES_PER_BRANCH);
            IF COUNT_SPECIES_PER_BRANCH = 1 THEN
                CALL DBMS_OUTPUT.PUT_LINE(V_BRANCH_NAME || ': ' || COUNT_SPECIES_PER_BRANCH
                                                            || ' брой от вид ' || V_SPECIES);
            ELSE
                CALL DBMS_OUTPUT.PUT_LINE(V_BRANCH_NAME || ': ' || COUNT_SPECIES_PER_BRANCH
                                                            || ' броя от вид ' || V_SPECIES);
            END IF;

            SET COUNT_SPECIES = COUNT_SPECIES + COUNT_SPECIES_PER_BRANCH;
            SET COUNTER = COUNTER + 1;
        END WHILE;

        IF MOD(COUNT_SPECIES, 5) = 0 THEN
            CALL DBMS_OUTPUT.PUT_LINE('Собственикът, чийто телефон е ' || n.CLIENT_PHONE
                                                 || ', спечели ваучер на стойност 15 лв');
        END IF;

        CLOSE CURSORBRANCHES;
    END;

INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) 
VALUES ('Кук', '23.11.2021', 'папагал', 'Ваксинация против аденовирус', '621479541100', '10.12.2021', '0887295128');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) 
VALUES ('Ину', '15.12.2021', 'папагал', 'Ваксинация против параинфлуенца вирус, Ваксинация против бяс', '728913648228', '28.12.2021', '0881464980');