SET SCHEMA FN71959;


INSERT INTO BRANCHES (NAME, ADDRESS) VALUES ('Пухкав свят - Варна', 'ул. Генерал Паренсов 52');
INSERT INTO BRANCHES (NAME, ADDRESS) VALUES ('Пухкав свят - Велико Търново', 'ул. M. Габровска 2A');
INSERT INTO BRANCHES (NAME, ADDRESS) VALUES ('Пухкав свят - София', 'ул. Пиер Дешейвър 10B');

INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Обстоен първичен преглед', 15, 30, 'първичен прием и консултация', 'Измерване на телесното тегло, вътрешна телесна температура, цвят на видими лигавици, тест за хидратация, преслушване на трахея, бели дробове и сърце, неврологичен статус, ортопедичен статус, кожен, очен и устен статус.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Рязане на нокти', 6, 10, 'първичен прием и консултация', '');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Консултация', 5, 20, 'първичен прием и консултация', 'Правилно профилактиране, породни особености, генетични предразположености, поведенчески проблеми, правилен начин на отглеждане.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Преглед и заверка на паспорт', 10, 5, 'първичен прием и консултация', '');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Външно обезпаразитяване', 12, 10, 'първичен прием и консултация', 'След като се разтвори козината на врата на животното, острият край на пипетата се поставя върху кожата и се изстисква съдържанието.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Вътрешно обезпаразитяване', 8, 5, 'първичен прием и консултация', 'Хапчето се слага внимателно на задната част на езика на животното, за да може да го преглътне безпроблемно.');

INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Плазмотерапия', 40, 30, 'терапевтични грижи', 'Цената се отнася за 1 посещение.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Криотерапия', 30, 20, 'терапевтични грижи', 'Цената се отнася за 1 посещение.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Физиотерапия', 10, 30, 'терапевтични грижи', 'Цената се отнася за 1 посещение.');

INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Първа ваксина за куче', 28, 5, 'ваксинация', 'Моновалентна P/бивалентна DP/тривалентна DHP. Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Втора ваксина за куче', 28, 5, 'ваксинация', 'Петвалентна DHP-L. Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Трета ваксина за куче', 28, 5, 'ваксинация', 'Шествалентна DHPPi-L/седемвалентна DHPPi-RL. Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Тривалентна ваксина за котка', 28, 5, 'ваксинация', 'Ваксина RCP. Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Петвалентна ваксина за котка', 55, 5, 'ваксинация', 'Ваксина RCPChFeLV. Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Ваксинация против бяс', 15.50, 5, 'ваксинация', 'Моновалентна  - R. Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Ваксинация против кучешка кашлица', 30, 5, 'ваксинация', 'Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Ваксинация против херпесвирус', 105, 5, 'ваксинация', 'Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Ваксинация против гъбични заболявания', 20, 5, 'ваксинация', 'Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Ваксинация против лептоспироза', 70, 5, 'ваксинация', 'Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Ваксинация против аденовирус', 55, 5, 'ваксинация', 'Ваксината е включена в цената.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Ваксинация против параинфлуенца вирус', 64, 5, 'ваксинация', 'Ваксината е включена в цената.');

INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Отстраняване на сливици', 120, 90, 'хирургични услуги и операции', '');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Кастрация', 60, 60, 'хирургични услуги и операции', '');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Цезарово сечение', 100, 120, 'хирургични услуги и операции', '');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Корекция ноздри', 120, 80, 'хирургични услуги и операции', '');

INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Почистване на зъбен камък с ултразвук', 50, 60, 'стоматологични услуги', '');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Почистване на зъбен камък инструментално', 25, 90, 'стоматологични услуги', 'С възможност за поставяне на локална упойка, която се заплаща допълнително.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Изваждане на млечен зъб', 38, 15, 'стоматологични услуги', 'С възможност за поставяне на локална упойка, която се заплаща допълнително.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Изваждане на постоянен зъб', 65, 15, 'стоматологични услуги', 'С възможност за поставяне на локална упойка, която се заплаща допълнително.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Изрязване на зъби на гризачи', 60, 20, 'стоматологични услуги', 'С възможност за поставяне на локална упойка, която се заплаща допълнително.');

INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Рентгенография', 25, 10, 'рентгенови изследвания', '');

INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Изследване на гръбначномозъчна течност', 75, 15, 'лабораторни изследвания', '');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Кожна проба', 35, 15, 'лабораторни изследвания', '');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Кръвна картина', 55, 20, 'лабораторни изследвания', 'Показва броя, съотношението и размера на различните клетки в кръвта.');
INSERT INTO SERVICES (NAME_PROCEDURE, PRICE, DURATION, AREA, DESCRIPTION) VALUES ('Кръвна натривка', 25, 15, 'лабораторни изследвания', 'Паразитите се наблюдават като точковидни включения в еритроцитите.');

INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Владимир Симеонов', 'гр. Варна, кв. Чайка 26В', '0887619355', '0884130163', 'Професионална гимназия по ветеринарна медицина "Иван П. Павлов" в гр. Стара Загора', 'Сертификат по терапия, Сертификат по диагностика', 'Пухкав свят - Варна');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Георги Михайлов', 'гр. София, ул. Пловдив 313A', '0885402746', '0884500427', 'Професионална гимназия по ветеринарна медицина "Проф. д-р Димитър Димов" в гр. Ловеч', 'Сертификат по стоматология', 'Пухкав свят - София');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Николай Юлианоя', 'гр. Велико Търново, ул. Ангел Кънчев 3A', '0883033541', '0882784061', 'Тракийски университет в гр. Стара Загора', 'Сертификат по вътрешна медицина', 'Пухкав свят - Велико Търново');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Васил Стоянов', 'гр. Варна, ул. Бузлуджа 4', '0881446435', '0889955328', 'Професионална гимназия по ветеринарна медицина "Проф. д-р Георги Павлов"', 'Сертификат по стоматология', 'Пухкав свят - Варна');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Валентин Миронов', 'гр. София, ул. Атанас Хранов 67B', '0884241408', '0887105399', 'Професионална гимназия по ветеринарна медицина и селско стопанство "СВ. Георги Победоносец" гр. Костинброд, 'Сертификат по терапия, Сертификат по диагностика', 'Пухкав свят - София');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Христо Христов', 'гр. Велико Търново, ул. Плиска 2В', '0876489421', '0887259084', 'Професионална гимназия по ветеринарна медицина "Иван П. Павлов" в гр. Стара Загора', 'Сертификат по терапия, Сертификат по диагностика', 'Пухкав свят - Велико Търново');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Мартин Йорданов', 'гр. Варна, ул. Околчица 23', '0872353814', '0881124984', 'Лесотехнически университет в гр. София ', 'Сертификат по хирургия', 'Пухкав свят - Варна');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Александра Христова', 'гр. София, ул. Христо Матов 22', '0872233584', '0882654099', 'Тракийски университет в гр. Стара Загора', 'Сертификат по вътрешна медицина', 'Пухкав свят - София');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Далия Димитрова', 'гр. Велико Търново, ул. Мария Габровска 6Г', '0878679254', '0885841922', 'Тракийски университет в гр. Стара Загора', 'Сертификат по хирургия', 'Пухкав свят - Велико Търново');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Габриела Михалева', 'гр. Варна, ул. Дрин 59', '0871457323', '0887790272', 'Тракийски университет в гр. Стара Загора', 'Сертификат по вътрешна медицина', 'Пухкав свят - Варна');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Агата Игликова', 'гр. София, ул. Цветна градина 52', '0895196449', '0889851223', 'Лесотехнически университет в гр. София ', 'Сертификат по хирургия', 'Пухкав свят - София');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Адриана Мутафова', 'гр. Велико Търново, ул. Симеон Велики 9E', '0899589438', '0886004335', 'Професионална гимназия по ветеринарна медицина "Проф. д-р Георги Павлов"', 'Сертификат по стоматология', 'Пухкав свят - Велико Търново');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Валентина Киркорова', 'гр. Варна, ул. Емануел Манолов 12A', '0898342016', '0885625555', 'Професионална гимназия по ветеринарна медицина "Проф. д-р Георги Павлов"', 'Сертификат по терапия, Сертификат по диагностика', 'Пухкав свят - Варна');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Даниела Евгениева', 'гр. София, ул. Методий Антонов 79B', '0894664459', '0883137495', 'Лесотехнически университет в гр. София ', 'Сертификат по хирургия', 'Пухкав свят - София');
INSERT INTO STAFF(NAME, ADDRESS, PHONE, WORK_NUMBER, VETERINARY_EDUCATION, ADDITIONAL_QUALIFICATIONS, BRANCH_NAME) VALUES ('Златина Карамфилова', 'гр. Велико Търново, ул. Черни връх 74', '0894643772', '0889929455', 'Тракийски университет в гр. Стара Загора', 'Сертификат по вътрешна медицина', 'Пухкав свят - Велико Търново');

INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Antiflegmin ointment', 250, 'крем', '2021-07-20', 'DWHIGN95923483', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Apoquel', 60, 'таблетки', '25.11.2021', 'XBUMGC86418292', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Bachus calm and brave', 80, 'таблетки', '13.12.2021', 'OEUWWW67299210', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Bayer Advantix Spot On', 40, 'пипети', '15.10.2021', 'NQCEFS30359527', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Ceva Vectra 3D', 32, 'пипети', '23.10.2021', 'YFKBKC59024452', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Endectovet', 24, 'таблетки', '07.02.2022', 'XFDDOY41024817', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Advantage@', 26, 'пипети', '27.03.2022', 'OATOEI28837042', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Profender spot-on', 30, 'таблетки', '12.12.2021', 'WVYNDA32441390', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Benzoylic peroxide shampoo', 300, 'шампоан', '09.06.2022', 'HKXHIZ04647094', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Dia tab', 20, 'таблетки', '19.04.2022', 'YIVMKN66263051', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Vitamin drops C', 120, 'капки', '12.01.2022', 'THCGFU05874537', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Daforte', 40, 'крем', '07.12.2021', 'DZBEMT97452556', 'Пухкав свят - Варна');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Local anesthesia', 9, 'течност', '14.11.2021', 'IBCGDN75030492', 'Пухкав свят - Варна');

INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Antiflegmin ointment', 50, 'крем', '2021-05-10', 'IPXXYZ44448814', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Apoquel', 50, 'таблетки', '22.10.2021', 'RBRDXI23317307', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Bachus calm and brave', 70, 'таблетки', '14.11.2021', 'SYTIEG03433952', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Bayer Advantix Spot On', 50, 'пипети', '07.09.2021', 'RCWRJW53968762', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Ceva Vectra 3D', 34, 'пипети', '17.10.2021', 'EWDMIB57544665', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Endectovet', 16, 'таблетки', '20.05.2021', 'UCALFD46806698', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Advantage@', 36, 'пипети', '28.03.2022', 'YXWQUE97019020', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Profender spot-on', 20, 'таблетки', '06.08.2021', 'KSGPTJ57470315', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Benzoylic peroxide shampoo', 350, 'шампоан', '18.05.2022', 'JJOMZJ70546900', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Dia tab', 10, 'таблетки', '13.03.2022', 'OIAXAT69711254', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Vitamin drops C', 170, 'капки', '26.02.2022', 'EFABCB38026336', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Daforte', 45, 'крем', '16.10.2021', 'AFOIYY46444238', 'Пухкав свят - Велико Търново');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Local anesthesia', 25, 'течност', '15.12.2021', 'FCXRGK23239934', 'Пухкав свят - Велико Търново');

INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Antiflegmin ointment', 270, 'крем', '2021-08-25', 'UJURQP94673923', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Apoquel', 40, 'таблетки', '13.12.2021', 'MXVARH45043300', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Bachus calm and brave', 90, 'таблетки', '10.11.2021', 'MEALIS81785766', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Bayer Advantix Spot On', 60, 'пипети', '09.10.2021', 'SQRMBF00813298', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Ceva Vectra 3D', 38, 'пипети', '21.09.2021', 'DEPGFB32910750', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Endectovet', 28, 'таблетки', '03.03.2022', 'NZRZOF60001669', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Advantage@', 14, 'пипети', '22.04.2022', 'MQTIWV70849923', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Profender spot-on', 34, 'таблетки', '14.11.2021', 'HLAMOC65116609', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Benzoylic peroxide shampoo', 380, 'шампоан', '19.08.2022', 'RITQCB97415748', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Dia tab', 26, 'таблетки', '18.05.2021', 'YTXBPA36296635', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Vitamin drops C', 100, 'капки', '16.02.2022', 'ZAMYLT79742439', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Daforte', 30, 'крем', '08.08.2021', 'LIAKCU10841990', 'Пухкав свят - София');
INSERT INTO CONSUMABLES(NAME, QUANTITY, TYPE_SUBSTANCE, EXPIRY_DATE, PRODUCTION_NUMBER, BRANCH_NAME) VALUES ('Local anesthesia', 40, 'течност', '06.10.2021', 'BHAOXN74047913', 'Пухкав свят - София');

INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Иван Драганов', 'гр. Варна, ул. Академик Андрей Сахаров 9', '0885556448', 'ivan.draganov@abv.bg');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Стойчо Желязков', 'гр. София, ул. Майор Юрий Гагарин 26', '0887295128', '');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Петър Славов', 'гр. Велико Търново, ул. Пейо К. Яворов 39', '0885709438', '');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Димитър Красимиров', 'гр. Варна, кв. Младост II 142', '0881129375', 'mitaka.krasimirov@gmail.com');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Кирил Трендафилов', 'гр. София, ул. Латинка 22', '0881464980', 'kltrendafilov@abv.bg');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Ивелина Славова', 'гр. Велико Търново, ул. Гео Милев 25', '0878292675', '');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Славена Атанасова', 'гр. Варна, кв. Младост I 105', '0871126896', 'slavencheto@mail.com');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Йоан Данаилов', 'гр. София, кв. Пейо К. Яворов 15', '0874908671', '');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Борис Александров', 'гр. Велико Търново, ул. Елин Пелин 21', '0877205233', 'bobi.aleksandrov@mail.com');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Виктория Минчева', 'гр. Варна, bул. Сливница 187Г', '0878316240', 'vikito168@gmail.com');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Мария Иванова', 'гр. София, кв. Сердика 6В', '0897607011', '');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Никол Николова', 'гр. Велико Търново, ул. Cvetarska 50', '0893440722', 'nikol.nikolova@abv.bg');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Симона Христова', 'гр. Варна, кв. Чайка 40', '0896080073', 'simonchetosh@mail.com');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Петя Стоименова', 'гр. София, кв. Света Троица 313B', '0899770572', '');
INSERT INTO CLIENTS (NAME, ADDRESS, PHONE, EMAIL) VALUES ('Пламена Тодорова', 'гр. Велико Търново, ул. Възрожденска 25', '0893878707', 'plamenatodorova@abv.bg');

INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Дикси', '20.06.2019', 'куче', 'Моновалентна  P ваксина', '010568817747', '14.03.2021', '0885556448');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Айзък', '07.09.2020', 'куче', 'Бивалентна DP ваксина', '174061547419', '16.04.2021', '0887295128');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Грейси', '13.05.2016', 'куче', 'Тривалентна DHP ваксина', '784003156890', '01.05.2021', '0885709438');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Нина', '15.12.2016', 'куче', 'Петвалентна DHP-L ваксина', '510659574726', '17.01.2021', '0899770572');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Шарко', '01.03.2013', 'куче', 'Седемвалентна DHPPi-RL ваксина', '664702033784', '25.02.2021', '0893878707');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Буба', '25.09.2017', 'котка', 'Тривалентна RCP ваксина', '358082839177', '13.02.2021', '0897607011');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Бончо', '18.04.2015', 'котка', 'Петвалентна RCPChFeLV ваксина', '507416148483', '19.04.2021', '0899770572');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Сузи', '22.06.2018', 'котка', 'Петвалентна RCPChFeLV ваксина', '833087222040', '18.04.2021', '0871126896');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Дано', '29.08.2020', 'котка', 'Петвалентна RCPChFeLV ваксина', '356930234381', '07.05.2021', '0881129375');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Маша', '12.03.2019', 'котка', 'Тривалентна RCP ваксина', '688487167257', '29.03.2021', '0893440722');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Анди', '23.08.2020', 'папагал', 'Ваксинация против лептоспироза, Ваксинация против аденовирус', '593438581005', '03.02.2021', '0887295128');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Умка', '10.02.2020', 'папагал', 'Ваксинация против параинфлуенца вирус, Ваксинация против бяс', '700905640722', '05.03.2021', '0881464980');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Зазу', '08.05.2019', 'папагал', 'Ваксинация против параинфлуенца вирус', '087207548339', '23.04.2021', '0896080073');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Попи', '09.09.2018', 'заек', 'Ваксинация против гъбични заболявания', '491075746688', '20.04.2021', '0874908671');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Блинки', '17.11.2020', 'заек', '', '429825539721', '17.05.2021', '0877205233');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Сънчо', '12.02.2021', 'морско свинче', 'Ваксинация против гъбични заболявания', '881630747943', '17.05.2021', '0878316240');
INSERT INTO ANIMALS (NAME, BIRTH_DATE, SPECIES, VACCINATIONS, CODE, LAST_VISIT, CLIENT_PHONE) VALUES ('Пухчо', '21.11.2020', 'хамстер', '', '217264968255', '12.04.2021', '0878292675');

INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('010568817747', 'Пухкав свят - Варна');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('174061547419', 'Пухкав свят - София');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('593438581005', 'Пухкав свят - София');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('784003156890', 'Пухкав свят - Велико Търново');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('356930234381', 'Пухкав свят - Варна');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('700905640722', 'Пухкав свят - София');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('217264968255', 'Пухкав свят - Велико Търново');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('833087222040', 'Пухкав свят - Варна');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('491075746688', 'Пухкав свят - София');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('429825539721', 'Пухкав свят - Велико Търново');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('881630747943', 'Пухкав свят - Варна');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('358082839177', 'Пухкав свят - София');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('688487167257', 'Пухкав свят - Велико Търново');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('087207548339', 'Пухкав свят - Варна');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('507416148483', 'Пухкав свят - София');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('510659574726', 'Пухкав свят - София');
INSERT INTO SERVES (ANIMAL_CODE, BRANCH_NAME) VALUES ('664702033784', 'Пухкав свят - Велико Търново');

INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Рентгенография', '0884130163');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Плазмотерапия', '0884130163');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Криотерапия', '0884130163');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Физиотерапия', '0884130163');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Рентгенография', '0887105399');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Плазмотерапия', '0887105399');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Криотерапия', '0887105399');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Физиотерапия', '0887105399');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Рентгенография', '0887259084');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Плазмотерапия', '0887259084');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Криотерапия', '0887259084');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Физиотерапия', '0887259084');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Рентгенография', '0885625555');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Плазмотерапия', '0885625555');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Криотерапия', '0885625555');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Физиотерапия', '0885625555');

INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Почистване на зъбен камък с ултразвук', '0884500427');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Почистване на зъбен камък инструментално', '0884500427');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изваждане на млечен зъб', '0884500427');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изваждане на постоянен зъб', '0884500427');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изрязване на зъби на гризачи', '0884500427');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Почистване на зъбен камък с ултразвук', '0889955328');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Почистване на зъбен камък инструментално', '0889955328');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изваждане на млечен зъб', '0889955328');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изваждане на постоянен зъб', '0889955328');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изрязване на зъби на гризачи', '0889955328');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Почистване на зъбен камък с ултразвук', '0886004335');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Почистване на зъбен камък инструментално', '0886004335');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изваждане на млечен зъб', '0886004335');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изваждане на постоянен зъб', '0886004335');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изрязване на зъби на гризачи', '0886004335');

INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изследване на гръбначномозъчна течност', '0882784061');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кожна проба', '0882784061');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кръвна картина', '0882784061');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кръвна натривка', '0882784061');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изследване на гръбначномозъчна течност', '0882654099');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кожна проба', '0882654099');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кръвна картина', '0882654099');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кръвна натривка', '0882654099');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изследване на гръбначномозъчна течност', '0887790272');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кожна проба', '0887790272');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кръвна картина', '0887790272');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кръвна натривка', '0887790272');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Изследване на гръбначномозъчна течност', '0889929455');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кожна проба', '0889929455');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кръвна картина', '0889929455');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кръвна натривка', '0889929455');

INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Отстраняване на сливици', '0881124984');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кастрация', '0881124984');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Цезарово сечение', '0881124984');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Корекция ноздри', '0881124984');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Отстраняване на сливици', '0885841922');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кастрация', '0885841922');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Цезарово сечение', '0885841922');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Корекция ноздри', '0885841922');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Отстраняване на сливици', '0889851223');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кастрация', '0889851223');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Цезарово сечение', '0889851223');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Корекция ноздри', '0889851223');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Отстраняване на сливици', '0883137495');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Кастрация', '0883137495');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Цезарово сечение', '0883137495');
INSERT INTO PERFORMS (SERVICE_NAME_PROCEDURE, STAFF_WORK_NUMBER) VALUES ('Корекция ноздри', '0883137495');